name: Automated Backup

on:
  push:
    branches: [ main, master ]
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Get full history
      
      - name: Create backup tag
        run: |
          DATE=$(date +'%Y-%m-%d-%H%M%S')
          git tag "backup-$DATE"
          git push origin "backup-$DATE"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Archive repository
        run: |
          DATE=$(date +'%Y-%m-%d')
          tar -czf "asteroids-backup-$DATE.tar.gz" \
            --exclude=node_modules \
            --exclude=dist \
            --exclude=.git \
            .
      
      - name: Upload backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: backup-${{ github.sha }}
          path: asteroids-backup-*.tar.gz
          retention-days: 90
